export enum PROVIDER_NAMES {
  GNOSIS = 'Gnosis',
  METAMASK = 'MetaMask',
  IM_TOKEN = 'imToken',
  TRUST = 'Trust',
  WALLET_CONNECT = 'WalletConnect',
  WALLET_LINK = 'WalletLink',
  COINBASE = 'Coinbase',
  INJECTED = 'Injected',
  LEDGER_HQ_LIVE = 'Ledger Live',
  LEDGER = 'Ledger',
  COIN98 = 'Coin98',
  MATH_WALLET = 'MathWallet',
  TALLY = 'Tally',
  BRAVE = 'Brave Wallet',
  EXODUS = 'Exodus',
}

export enum CONNECTOR_NAMES {
  GNOSIS = 'gnosis',
  WALLET_CONNECT = 'walletconnect',
  WALLET_CONNECT_URI = 'WalletConnectUri',
  WALLET_CONNECT_NOLINKS = 'WalletConnectNoLinks',
  WALLET_LINK = 'walletlink',
  COINBASE = 'coinbase',
  INJECTED = 'injected',
  LEDGER_HQ_LIVE = 'ledgerlive',
  LEDGER = 'ledger',
  EXODUS = 'exodus',
}
